// module#2
let $ = require('jquery')
let _ = require('lodash');
$(document).ready(function () {
  let people = [{
    "id": 1,
    "first_name": "Bryon",
    "last_name": "Turvey",
    "email": "bturvey0@state.tx.us",
    "gender": "Male",
    "ip_address": "2.244.117.208"
  }, {
    "id": 2,
    "first_name": "Sol",
    "last_name": "Churchlow",
    "email": "schurchlow1@narod.ru",
    "gender": "Male",
    "ip_address": "170.208.174.230"
  }, {
    "id": 3,
    "first_name": "Pauletta",
    "last_name": "Gravenor",
    "email": "pgravenor2@ning.com",
    "gender": "Female",
    "ip_address": "0.16.19.163"
  }, {
    "id": 4,
    "first_name": "Odele",
    "last_name": "Dunston",
    "email": "odunston3@google.pl",
    "gender": "Female",
    "ip_address": "45.152.178.77"
  }, {
    "id": 5,
    "first_name": "Hannah",
    "last_name": "Wooderson",
    "email": "hwooderson4@uol.com.br",
    "gender": "Female",
    "ip_address": "197.21.90.115"
  }, {
    "id": 6,
    "first_name": "Ky",
    "last_name": "Gilders",
    "email": "kgilders5@ifeng.com",
    "gender": "Male",
    "ip_address": "243.172.222.50"
  }, {
    "id": 7,
    "first_name": "Derrick",
    "last_name": "Towhey",
    "email": "dtowhey6@redcross.org",
    "gender": "Male",
    "ip_address": "100.230.223.136"
  }, {
    "id": 8,
    "first_name": "Emmalynn",
    "last_name": "Pavlitschek",
    "email": "epavlitschek7@slideshare.net",
    "gender": "Female",
    "ip_address": "223.41.217.130"
  }, {
    "id": 9,
    "first_name": "Dexter",
    "last_name": "Olwen",
    "email": "dolwen8@webs.com",
    "gender": "Male",
    "ip_address": "185.107.37.233"
  }, {
    "id": 10,
    "first_name": "Lotty",
    "last_name": "McBay",
    "email": "lmcbay9@purevolume.com",
    "gender": "Female",
    "ip_address": "246.112.18.226"
  }, {
    "id": 11,
    "first_name": "Gerri",
    "last_name": "Budnk",
    "email": "gbudnka@sciencedirect.com",
    "gender": "Male",
    "ip_address": "117.135.233.210"
  }, {
    "id": 12,
    "first_name": "Hilly",
    "last_name": "Ramas",
    "email": "hramasb@dion.ne.jp",
    "gender": "Male",
    "ip_address": "138.15.0.205"
  }, {
    "id": 13,
    "first_name": "Deanna",
    "last_name": "Tilliard",
    "email": "dtilliardc@nifty.com",
    "gender": "Female",
    "ip_address": "57.111.112.250"
  }, {
    "id": 14,
    "first_name": "Quill",
    "last_name": "Finlow",
    "email": "qfinlowd@ted.com",
    "gender": "Male",
    "ip_address": "8.227.22.63"
  }, {
    "id": 15,
    "first_name": "Roscoe",
    "last_name": "McCorkell",
    "email": "rmccorkelle@shop-pro.jp",
    "gender": "Male",
    "ip_address": "91.118.33.159"
  }, {
    "id": 16,
    "first_name": "Dilan",
    "last_name": "Baskeyfied",
    "email": "dbaskeyfiedf@google.fr",
    "gender": "Male",
    "ip_address": "156.128.4.7"
  }, {
    "id": 17,
    "first_name": "Branden",
    "last_name": "Proback",
    "email": "bprobackg@domainmarket.com",
    "gender": "Male",
    "ip_address": "211.152.222.54"
  }, {
    "id": 18,
    "first_name": "Olenolin",
    "last_name": "Cattlemull",
    "email": "ocattlemullh@fc2.com",
    "gender": "Male",
    "ip_address": "35.161.163.248"
  }, {
    "id": 19,
    "first_name": "Lissi",
    "last_name": "Floyed",
    "email": "lfloyedi@latimes.com",
    "gender": "Female",
    "ip_address": "236.190.202.226"
  }, {
    "id": 20,
    "first_name": "Lorrie",
    "last_name": "Housecraft",
    "email": "lhousecraftj@unicef.org",
    "gender": "Male",
    "ip_address": "164.153.191.46"
  }]
  let genderPeople = _.filter(people, {gender: "Male"}).length

  let body = document.getElementsByTagName('body')[0];
  let h2 = document.createElement('h2')
  body.appendChild(h2);
  $('h2').html("There are " + genderPeople + " males in the sample data!")

  console.log("mod 2");
})
